language: java
jdk: openjdk8
install: true
script: mvn -Powasp org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.javadoc.skip=true -B sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
